---

- include: wrk.yml

- name: Ensure that frameworks directory is exists
  file: state=directory path={{setup_prefix}}/{{item}}
  with_items: setup_frameworks

- name: Link sources
  file: state=link src={{setup_source}}/{{item}} dest={{setup_prefix}}/{{item}}/src
  with_items: setup_frameworks

- name: Setup virtualenvs
  pip: requirements={{setup_prefix}}/{{item}}/src/requirements.txt virtualenv={{setup_prefix}}/{{item}}/env virtualenv_command=virtualenv-3.4
  with_items: setup_frameworks

- name: Setup services
  template: src=upstart.conf dest=/etc/init/{{item}}.conf
  with_items: setup_frameworks

- name: Setup test scripts
  template: src=test.sh dest={{setup_prefix}}/{{item}}/test.sh mode=0755
  with_items: setup_frameworks

- name: Copy SQL dump
  copy: src=dump.sql dest={{setup_prefix}}/dump.sql

- name: Load SQL dump
  shell: psql benchmark < {{setup_prefix}}/dump.sql
  sudo: yes
  sudo_user: postgres
